// Language translations for Hanime
// Complete translations for all supported languages

const translations = {
    en: {
        title: "Hanime — Anime Hentai Stream | Download APK",
        tagline: "Uncensored. Unlimited. Ultimate Experience.",
        subtitle: "#1 Anime Hentai Streaming",
        download: "Download APK",
        explore: "Features",
        heroDesc: "Stream thousands of hentai OVAs, uncensored episodes, and exclusive anime in crisp 1080p/4K. Get the official Hanime Android APK and enjoy ad-free, offline mode, and early access.",
        loading: "Loading...",
        downloading: "Downloading Hanime APK...",
        downloadStarted: "Download started: Hanime_v4.2.1.apk — check notifications.",
        downloadError: "Download failed. Please try again.",
        appName: "Hanime Official App",
        appVersion: "v4.2.1 • APK 28MB",
        sectionTitle: "Hot Picks · Exclusive Leaks",
        bannerTitle: "Hanime APK – Premium Unlocked",
        bannerDesc: "Download latest version (v4.2.1) • Uncensored streams • Offline mode • No region lock",
        bannerBtn: "Download APK (Direct)",
        statUsers: "500k+ Downloads",
        statVideos: "3,200+ Titles",
        statSync: "4.8 ★ Rating",
        feat1Title: "Uncensored HD",
        feat1Desc: "True 1080p/4K quality, no mosaics",
        feat2Title: "Massive Library",
        feat2Desc: "3200+ titles + weekly updates",
        feat3Title: "Offline Mode",
        feat3Desc: "Download episodes & watch anytime",
        feat4Title: "Lightning Fast",
        feat4Desc: "Optimized streaming engine",
        footerNote: "© 2025 Hanime — The ultimate hentai streaming platform. All trademarks belong to their respective owners.",
        ctaNote2: "Safe & secure APK • No ads inside app • 18+ only"
    },
    ja: {
        title: "Hanime — アニメHentaiストリーム | APKダウンロード",
        tagline: "無修正。無制限。究極の体験。",
        subtitle: "#1 アニメHentaiストリーミング",
        download: "APKをダウンロード",
        explore: "機能",
        heroDesc: "数千のHentai OVA、無修正エピソード、独占アニメを鮮明な1080p/4Kでストリーミング。公式Hanime Android APKを入手して、広告なし、オフラインモード、早期アクセスをお楽しみください。",
        loading: "読み込み中...",
        downloading: "Hanime APKをダウンロード中...",
        downloadStarted: "ダウンロード開始: Hanime_v4.2.1.apk — 通知を確認してください。",
        downloadError: "ダウンロードに失敗しました。もう一度お試しください。",
        appName: "Hanime 公式アプリ",
        appVersion: "v4.2.1 • APK 28MB",
        sectionTitle: "人気のおすすめ · 独占リーク",
        bannerTitle: "Hanime APK – プレミアムアンロック",
        bannerDesc: "最新バージョンをダウンロード (v4.2.1) • 無修正ストリーム • オフラインモード • 地域制限なし",
        bannerBtn: "APKをダウンロード（直接）",
        statUsers: "50万以上のダウンロード",
        statVideos: "3,200以上のタイトル",
        statSync: "4.8星評価",
        feat1Title: "無修正HD",
        feat1Desc: "本物の1080p/4K画質、モザイクなし",
        feat2Title: "大規模ライブラリ",
        feat2Desc: "3200以上のタイトル+週次更新",
        feat3Title: "オフラインモード",
        feat3Desc: "エピソードをダウンロードしていつでも視聴",
        feat4Title: "超高速",
        feat4Desc: "最適化されたストリーミングエンジン",
        footerNote: "© 2025 Hanime — 究極のhentaiストリーミングプラットフォーム。すべての商標はそれぞれの所有者に帰属します。",
        ctaNote2: "安全なAPK • アプリ内に広告なし • 18歳以上のみ"
    },
    zh: {
        title: "Hanime — 动漫Hentai直播 | 下载APK",
        tagline: "无修正。无限。终极体验。",
        subtitle: "#1 动漫Hentai直播平台",
        download: "下载APK",
        explore: "功能",
        heroDesc: "直播数千个Hentai OVA、无修正剧集和独家动漫，清晰1080p/4K。获取官方Hanime Android APK，享受无广告、离线模式和提前访问。",
        loading: "加载中...",
        downloading: "正在下载Hanime APK...",
        downloadStarted: "下载开始: Hanime_v4.2.1.apk — 检查通知。",
        downloadError: "下载失败。请重试。",
        appName: "Hanime 官方应用",
        appVersion: "v4.2.1 • APK 28MB",
        sectionTitle: "热门精选 · 独家泄露",
        bannerTitle: "Hanime APK – 高级解锁",
        bannerDesc: "下载最新版本 (v4.2.1) • 无修正直播 • 离线模式 • 无地区限制",
        bannerBtn: "下载APK（直接）",
        statUsers: "50万+下载量",
        statVideos: "3,200+标题",
        statSync: "4.8星评分",
        feat1Title: "无修正高清",
        feat1Desc: "真正的1080p/4K画质，无马赛克",
        feat2Title: "海量库",
        feat2Desc: "3200+标题+每周更新",
        feat3Title: "离线模式",
        feat3Desc: "下载剧集，随时观看",
        feat4Title: "闪电般快速",
        feat4Desc: "优化的直播引擎",
        footerNote: "© 2025 Hanime — 终极hentai直播平台。所有商标归其各自所有者。",
        ctaNote2: "安全可靠的APK • 应用内无广告 • 仅限18+"
    },
    es: {
        title: "Hanime — Anime Hentai Stream | Descargar APK",
        tagline: "Sin censura. Ilimitado. Experiencia definitiva.",
        subtitle: "#1 Streaming de Anime Hentai",
        download: "Descargar APK",
        explore: "Características",
        heroDesc: "Transmite miles de OVAs hentai, episodios sin censura y anime exclusivo en 1080p/4K nítido. Obtén el APK oficial de Hanime para Android y disfruta sin anuncios, modo offline y acceso anticipado.",
        loading: "Cargando...",
        downloading: "Descargando Hanime APK...",
        downloadStarted: "Descarga iniciada: Hanime_v4.2.1.apk — revisa las notificaciones.",
        downloadError: "Descarga fallida. Por favor, inténtalo de nuevo.",
        appName: "Aplicación Oficial de Hanime",
        appVersion: "v4.2.1 • APK 28MB",
        sectionTitle: "Los Más Vistos • Fugas Exclusivas",
        bannerTitle: "Hanime APK – Premium Desbloqueado",
        bannerDesc: "Descarga la última versión (v4.2.1) • Streams sin censura • Modo offline • Sin bloqueo regional",
        bannerBtn: "Descargar APK (Directo)",
        statUsers: "500k+ Descargas",
        statVideos: "3,200+ Títulos",
        statSync: "4.8 ★ Calificación",
        feat1Title: "HD Sin Censura",
        feat1Desc: "Calidad real 1080p/4K, sin mosaicos",
        feat2Title: "Biblioteca Masiva",
        feat2Desc: "3200+ títulos + actualizaciones semanales",
        feat3Title: "Modo Offline",
        feat3Desc: "Descarga episodios y mira cuando quieras",
        feat4Title: "Ultra Rápido",
        feat4Desc: "Motor de streaming optimizado",
        footerNote: "© 2025 Hanime — La plataforma definitiva de streaming hentai. Todas las marcas comerciales pertenecen a sus respectivos propietarios.",
        ctaNote2: "APK segura • Sin anuncios en la app • Solo +18"
    },
    fr: {
        title: "Hanime — Anime Hentai Stream | Télécharger APK",
        tagline: "Sans censure. Illimité. Expérience ultime.",
        subtitle: "#1 Streaming de Anime Hentai",
        download: "Télécharger APK",
        explore: "Fonctionnalités",
        heroDesc: "Diffusez des milliers d'OVA hentai, d'épisodes sans censure et d'anime exclusifs en 1080p/4K net. Obtenez l'APK officiel Hanime pour Android et profitez sans publicité, mode hors ligne et accès anticipé.",
        loading: "Chargement...",
        downloading: "Téléchargement de Hanime APK...",
        downloadStarted: "Téléchargement commencé: Hanime_v4.2.1.apk — vérifiez les notifications.",
        downloadError: "Téléchargement échoué. Veuillez réessayer.",
        appName: "Application Officielle Hanime",
        appVersion: "v4.2.1 • APK 28MB",
        sectionTitle: "Les Plus Populaires • Fuites Exclusives",
        bannerTitle: "Hanime APK – Premium Débloqué",
        bannerDesc: "Télécharger la dernière version (v4.2.1) • Streams sans censure • Mode hors ligne • Pas de verrouillage régional",
        bannerBtn: "Télécharger APK (Direct)",
        statUsers: "500k+ Téléchargements",
        statVideos: "3,200+ Titres",
        statSync: "4.8 ★ Note",
        feat1Title: "HD Sans Censure",
        feat1Desc: "Vraie qualité 1080p/4K, sans mosaïques",
        feat2Title: "Bibliothèque Massive",
        feat2Desc: "3200+ titres + mises à jour hebdomadaires",
        feat3Title: "Mode Hors Ligne",
        feat3Desc: "Téléchargez les épisodes et regardez quand vous voulez",
        feat4Title: "Ultra Rapide",
        feat4Desc: "Moteur de streaming optimisé",
        footerNote: "© 2025 Hanime — La plateforme de streaming hentai ultime. Toutes les marques appartiennent à leurs propriétaires respectifs.",
        ctaNote2: "APK sécurisée • Pas de pub dans l'app • +18 seulement"
    },
    de: {
        title: "Hanime — Anime Hentai Stream | APK Herunterladen",
        tagline: "Unzensiert. Unbegrenzt. Ultimative Erfahrung.",
        subtitle: "#1 Anime Hentai Streaming",
        download: "APK Herunterladen",
        explore: "Funktionen",
        heroDesc: "Streamen Sie Tausende von Hentai-OVAs, unzensierte Folgen und exklusive Anime in kristallklarem 1080p/4K. Holen Sie sich die offizielle Hanime-Android-APK und genießen Sie werbefrei, Offline-Modus und frühen Zugang.",
        loading: "Laden...",
        downloading: "Hanime APK wird heruntergeladen...",
        downloadStarted: "Download gestartet: Hanime_v4.2.1.apk — Benachrichtigungen prüfen.",
        downloadError: "Download fehlgeschlagen. Bitte versuchen Sie es erneut.",
        appName: "Hanime Offizielle App",
        appVersion: "v4.2.1 • APK 28MB",
        sectionTitle: "Top-Auswahl • Exklusive Leaks",
        bannerTitle: "Hanime APK – Premium Freigeschaltet",
        bannerDesc: "Neueste Version herunterladen (v4.2.1) • Unzensierte Streams • Offline-Modus • Keine Regionalsperre",
        bannerBtn: "APK Herunterladen (Direkt)",
        statUsers: "500k+ Downloads",
        statVideos: "3,200+ Titel",
        statSync: "4.8 ★ Bewertung",
        feat1Title: "Unzensiertes HD",
        feat1Desc: "Echte 1080p/4K-Qualität, keine Mosaike",
        feat2Title: "Riesige Bibliothek",
        feat2Desc: "3200+ Titel + wöchentliche Updates",
        feat3Title: "Offline-Modus",
        feat3Desc: "Episoden herunterladen und jederzeit ansehen",
        feat4Title: "Blitzschnell",
        feat4Desc: "Optimierter Streaming-Motor",
        footerNote: "© 2025 Hanime — Die ultimative Hentai-Streaming-Plattform. Alle Marken gehören ihren jeweiligen Eigentümern.",
        ctaNote2: "Sichere APK • Keine Werbung in der App • Nur 18+"
    },
    hi: {
        title: "Hanime — एनीमे हेंटाई स्ट्रीम | APK डाउनलोड करें",
        tagline: "अनसेंसर्ड। असीमित। परम अनुभव।",
        subtitle: "#1 एनीमे हेंटाई स्ट्रीमिंग",
        download: "APK डाउनलोड करें",
        explore: "सुविधाएं",
        heroDesc: "हजारों हेंटाई OVA, अनसेंसर्ड एपिसोड और एक्सक्लूसिव एनीमे को क्रिस्टल क्लियर 1080p/4K में स्ट्रीम करें। आधिकारिक Hanime Android APK प्राप्त करें और विज्ञापन-मुक्त, ऑफ़लाइन मोड और जल्दी पहुंच का आनंद लें।",
        loading: "लोड हो रहा है...",
        downloading: "Hanime APK डाउनलोड हो रहा है...",
        downloadStarted: "डाउनलोड शुरू: Hanime_v4.2.1.apk — सूचनाएं जांचें।",
        downloadError: "डाउनलोड विफल। कृपया पुनः प्रयास करें।",
        appName: "Hanime आधिकारिक ऐप",
        appVersion: "v4.2.1 • APK 28MB",
        sectionTitle: "लोकप्रिय चयन • एक्सक्लूसिव लीक",
        bannerTitle: "Hanime APK – प्रीमियम अनलॉक",
        bannerDesc: "नवीनतम संस्करण डाउनलोड करें (v4.2.1) • अनसेंसर्ड स्ट्रीम • ऑफ़लाइन मोड • कोई क्षेत्रीय बंदिश नहीं",
        bannerBtn: "APK डाउनलोड करें (प्रत्यक्ष)",
        statUsers: "500k+ डाउनलोड",
        statVideos: "3,200+ शीर्षक",
        statSync: "4.8 ★ रेटिंग",
        feat1Title: "अनसेंसर्ड HD",
        feat1Desc: "वास्तविक 1080p/4K गुणवत्ता, कोई मोज़ेक नहीं",
        feat2Title: "विशाल लाइब्रेरी",
        feat2Desc: "3200+ शीर्षक + साप्ताहिक अपडेट",
        feat3Title: "ऑफ़लाइन मोड",
        feat3Desc: "एपिसोड डाउनलोड करें और कभी भी देखें",
        feat4Title: "तेज़ रफ़्तार",
        feat4Desc: "अनुकूलित स्ट्रीमिंग इंजन",
        footerNote: "© 2025 Hanime — परम हेंटाई स्ट्रीमिंग प्लेटफॉर्म। सभी ट्रेडमार्क उनके संबंधित मालिकों के हैं।",
        ctaNote2: "सुरक्षित APK • ऐप में कोई विज्ञापन नहीं • केवल 18+"
    },
    pt: {
        title: "Hanime — Anime Hentai Stream | Baixar APK",
        tagline: "Sem censura. Ilimitado. Experiência definitiva.",
        subtitle: "#1 Streaming de Anime Hentai",
        download: "Baixar APK",
        explore: "Recursos",
        heroDesc: "Assista milhares de OVAs hentai, episódios sem censura e animes exclusivos em 1080p/4K nítido. Obtenha o APK oficial do Hanime para Android e aproveite sem anúncios, modo offline e acesso antecipado.",
        loading: "Carregando...",
        downloading: "Baixando Hanime APK...",
        downloadStarted: "Download iniciado: Hanime_v4.2.1.apk — verifique as notificações.",
        downloadError: "Download falhou. Por favor, tente novamente.",
        appName: "Aplicativo Oficial Hanime",
        appVersion: "v4.2.1 • APK 28MB",
        sectionTitle: "Mais Vistos • Vazamentos Exclusivos",
        bannerTitle: "Hanime APK – Premium Desbloqueado",
        bannerDesc: "Baixar versão mais recente (v4.2.1) • Streams sem censura • Modo offline • Sem bloqueio regional",
        bannerBtn: "Baixar APK (Direto)",
        statUsers: "500k+ Downloads",
        statVideos: "3,200+ Títulos",
        statSync: "4.8 ★ Avaliação",
        feat1Title: "HD Sem Censura",
        feat1Desc: "Qualidade real 1080p/4K, sem mosaicos",
        feat2Title: "Biblioteca Massiva",
        feat2Desc: "3200+ títulos + atualizações semanais",
        feat3Title: "Modo Offline",
        feat3Desc: "Baixe episódios e assista quando quiser",
        feat4Title: "Ultra Rápido",
        feat4Desc: "Motor de streaming otimizado",
        footerNote: "© 2025 Hanime — A plataforma definitiva de streaming hentai. Todas as marcas comerciais pertencem aos seus respectivos proprietários.",
        ctaNote2: "APK seguro • Sem anúncios no app • Apenas +18"
    },
    ar: {
        title: "Hanime — سترييم أنمي هنتاي | تحميل APK",
        tagline: "بدون رقابة. غير محدود. التجربة القصوى.",
        subtitle: "#1 سترييم أنمي هنتاي",
        download: "تحميل APK",
        explore: "الميزات",
        heroDesc: "شاهد آلاف OVAs الهنتاي والحلقات غير الرقابية والأنمي الحصري بجودة 1080p/4K واضحة. احصل على APK Hanime الرسمي لنظام Android واستمتع بدون إعلانات ووضع بدون إنترنت ووصول مبكر.",
        loading: "جاري التحميل...",
        downloading: "جاري تحميل Hanime APK...",
        downloadStarted: "بدأ التنزيل: Hanime_v4.2.1.apk — تحقق من الإشعارات.",
        downloadError: "فشل التنزيل. يرجى المحاولة مرة أخرى.",
        appName: "تطبيق Hanime الرسمي",
        appVersion: "v4.2.1 • APK 28MB",
        sectionTitle: "الأكثر مشاهدة · تسريبات حصرية",
        bannerTitle: "Hanime APK – المميزات غير مقفلة",
        bannerDesc: "تنزيل أحدث إصدار (v4.2.1) • سترييم بدون رقابة • وضع بدون إنترنت • بدون قفل إقليمي",
        bannerBtn: "تحميل APK (مباشر)",
        statUsers: "500k+ تنزيلات",
        statVideos: "3,200+ عنوان",
        statSync: "4.8 ★ تقييم",
        feat1Title: "دقة عالية بدون رقابة",
        feat1Desc: "جودة حقيقية 1080p/4K، بدون فسيفساء",
        feat2Title: "مكتبة ضخمة",
        feat2Desc: "3200+ عنوان + تحديثات أسبوعية",
        feat3Title: "وضع بدون إنترنت",
        feat3Desc: "نزّل الحلقات وشاهد متى شئت",
        feat4Title: "فائق السرعة",
        feat4Desc: "محرك سترييم محسّن",
        footerNote: "© 2025 Hanime — منصة سترييم الهنتاي النهائية. جميع العلامات التجارية مملوكة لأصحابها.",
        ctaNote2: "APK آمن • بدون إعلانات في التطبيق +18 فقط"
    }
};

// Language names in native script
const languageNames = {
    en: "English",
    ja: "日本語",
    zh: "中文",
    es: "Español",
    fr: "Français",
    de: "Deutsch",
    hi: "हिन्दी",
    pt: "Português",
    ar: "العربية"
};

// RTL languages - Add languages that read right-to-left
const rtlLanguages = ['ar'];
